version: "3.4"
services:
  web-api:
    container_name: csharp
    image: esb/dashboard:1.0.0
    build:
      context: ./dotnet-docker
      target: debug
    volumes:
    - ./dotnet-docker/:/work/
    ports:
      - 5165:5165
      - 7030:7030
  client:
    build: ./angular-docker/
    ports: 
      - "4200:4200"
    volumes:
      - "./angular-docker:/app"
      - "/app/node_modules"